### ISSUE TITLE
Undefined array key "set_time_limit"

### ISSUE THREAD

**Issue by rodber** [chevereto/installer-source#11]
Getting this, likely happens for people using shared/limited servers.

**Comment by rodber** [comment]
```
[B]Aw, snap![/B] [debug @ print,error_log] - https://v3-docs.chevereto.com/setup/debug.html

[B]Fatal error [0]:[/B] Undefined array key "set_time_limit"
Triggered in installer.php:761

[B]Stack trace:[/B]
#0 installer.php(761): {closure}()
#1 installer.php(742): Runtime->applyPHPSettings()
#2 installer.php(1615): Runtime->run()
```

**Comment by rodber** [comment]
https://github.com/Chevereto/installer/blob/master/installer.php#L746
